# Generated by Django 4.0.6 on 2022-07-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=225, null=True, verbose_name='關鍵字')),
                ('status', models.CharField(max_length=225, null=True, verbose_name='狀態')),
                ('mode', models.CharField(max_length=225, null=True, verbose_name='比對模式')),
                ('search_request', models.CharField(max_length=225, null=True, verbose_name='搜尋请求')),
                ('view', models.IntegerField(blank=True, null=True, verbose_name='瀏覽數')),
                ('click', models.IntegerField(blank=True, null=True, verbose_name='點擊數')),
                ('click_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='點擊率')),
                ('transfer', models.IntegerField(blank=True, null=True, verbose_name='轉換')),
                ('dtransfer', models.IntegerField(blank=True, null=True, verbose_name='直接轉換')),
                ('transfer_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='轉換率')),
                ('dtransfer_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='直接轉換率')),
                ('cost_transfer', models.FloatField(blank=True, default=None, null=True, verbose_name='每一筆轉換的成本')),
                ('cost_dtransfer', models.FloatField(blank=True, default=None, null=True, verbose_name='每一筆轉換的成本')),
                ('sold_number', models.IntegerField(blank=True, null=True, verbose_name='銷售數')),
                ('dsold_number', models.IntegerField(blank=True, null=True, verbose_name='直接銷售數')),
                ('sold_cost', models.IntegerField(blank=True, null=True, verbose_name='銷售金額')),
                ('sold_dcost', models.IntegerField(blank=True, null=True, verbose_name='直接銷售金額')),
                ('cost', models.FloatField(blank=True, default=None, null=True, verbose_name='花費')),
                ('avg_rank', models.FloatField(blank=True, default=None, null=True, verbose_name='平均排名')),
                ('invent_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='投資產出比')),
                ('dinvent_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='直接投資產出比')),
                ('cost_revenue_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='成本收入比率')),
                ('dcost_revenue_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='直接成本收入比率')),
            ],
            options={
                'verbose_name': '商品資訊',
                'verbose_name_plural': '商品資訊',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=225, null=True, verbose_name='關鍵字')),
                ('store_id', models.CharField(max_length=225, null=True, verbose_name='賣場ID')),
                ('product_id', models.CharField(max_length=225, null=True, verbose_name='商品ID')),
                ('date_1', models.DateField(verbose_name='期間1')),
                ('date_2', models.DateField(verbose_name='期間2')),
                ('status', models.CharField(max_length=225, null=True, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '詮釋資料',
                'verbose_name_plural': '詮釋資料',
            },
        ),
    ]
