# Generated by Django 4.0.6 on 2022-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_search', models.FloatField(blank=True, default=None, null=True, verbose_name='瀏覽數')),
                ('total_transfer', models.FloatField(blank=True, default=None, null=True, verbose_name='轉換')),
                ('total_click', models.FloatField(blank=True, default=None, null=True, verbose_name='點擊數')),
                ('total_dtransfer', models.FloatField(blank=True, default=None, null=True, verbose_name='直接轉換')),
                ('total_cost', models.FloatField(blank=True, default=None, null=True, verbose_name='花費')),
                ('total_sell', models.FloatField(blank=True, default=None, null=True, verbose_name='銷售數')),
                ('total_tsell', models.FloatField(blank=True, default=None, null=True, verbose_name='直接銷售數')),
                ('average_rank', models.FloatField(blank=True, default=None, null=True, verbose_name='平均排名')),
                ('total_money', models.FloatField(blank=True, default=None, null=True, verbose_name='直接銷售金額')),
                ('total_tmoney', models.FloatField(blank=True, default=None, null=True, verbose_name='直接銷售金額')),
            ],
            options={
                'verbose_name': '統計資料',
                'verbose_name_plural': '統計資料',
            },
        ),
    ]
