# Generated by Django 4.0.6 on 2022-07-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_caldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='addata',
            name='meta_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.metadata'),
        ),
        migrations.AddField(
            model_name='caldata',
            name='meta_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.metadata'),
        ),
    ]
