# Generated by Django 4.0.6 on 2022-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0003_addata_meta_data_caldata_meta_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('product', 'store_id', 'product_id', 'date_1', 'date_2', 'status'), name='unique_migration_host_combination'),
        ),
    ]
